### ISSUE TITLE
Bottom Tab Navigator

### ISSUE THREAD

**Issue by IgarMikhailov** [TheCrazyAvenger/rn-progressio-app#1]
Please, double-check the logic, I think you don't need the TouchableOpacity there, it is excessive. Everything should work without this  component
https://reactnavigation.org/docs/tab-based-navigation#customizing-the-appearance

**Comment by IlliaPauliushchyk** [comment]
👍

чц, 4 ліс 2021, 22:12 карыстальнік Igar Mikhailov ***@***.***>
напісаў:
